# -*- coding: utf-8 -*-
"""Webscrapping

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yXQfasony_jjuRqqBBipqnaS7GWwFH1b
"""

import urllib.request, json, pandas as pd

new_url = "https://shopee.co.id/api/v4/search/search_items?by=relevancy&keyword=elektonik&limit=20&newest=0&order=desc&page_type=search&scenario=PAGE_GLOBAL_SEARCH&version=2"

df_item_baru = pd.DataFrame()
with urllib.request.urlopen(new_url) as url:
    data = json.loads(url.read().decode())
    df_new_url = pd.DataFrame.from_dict(data, orient = 'index')

df_new_url = pd.DataFrame(df_new_url.transpose())

df_item = pd.DataFrame(df_new_url['items'])

df_item = pd.DataFrame(df_item['items'].values.tolist())

df_item = df_item.transpose()

df_items = pd.DataFrame(df_item[0].values.tolist())

df_item_baru = df_item_baru.append(df_items, ignore_index = True)

df_item_baru = pd.DataFrame(df_item_baru['item_basic'].values.tolist())

shoppe_item = pd.DataFrame(df_item_baru[['name','price']])

shoppe_item['price'] = shoppe_item['price'].apply(lambda x: "Rp {:.2f}".format((x/100000)))

print(shoppe_item)